### ISSUE TITLE
fix for acts-as-dag 1.x (Rails 2.3.x)

### ISSUE THREAD

**Issue by ghost** [resgraph/acts-as-dag#14]
Hi! We're using acts-as-dag 1.x with Rails 2.3.x. Just fixed a bug that occurred when inserting child/parent nodes directly to the associations. Rails will do that in a create scope and then use the wrong attributes when instantiating bridging legs.

I cannot make a pull request as there's no 1.x branch in your repository. But see [this diff](https://github.com/jerico-dev/acts-as-dag/compare/resgraph:v1.1.3...v1.x?expand=1) to check my change.

If you create and push a 1.x branch at the v1.1.3 tag I'll be able to make a proper pull request to this branch.

**Comment by resgraph** [comment]
Cool Thanks. Will review and work into the code.

On 1/31/14, 11:48 PM, jerico-dev wrote:

> Hi! We're using acts-as-dag 1.x with Rails 2.3.x. Just fixed a bug 
> that occurred when inserting child/parent nodes directly to the 
> associations. Rails will do that in a create scope and then use the 
> wrong attributes when instantiating bridging legs.
> 
> I cannot make a pull request as there's no 1.x branch in your 
> repository. But see this diff 
> https://github.com/jerico-dev/acts-as-dag/compare/resgraph:v1.1.3...v1.x?expand=1 
> to check my change.
> 
> If you create and push a 1.x branch at the v1.1.3 tag I'll be able to 
> make a proper pull request to this branch.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/resgraph/acts-as-dag/issues/14.

## 

Signature
Robert A. Schmitt
Chief Executive Officer

_Concept *_Yard *
bright ideas, bright minds.
*
*
+1 (805) 403-0832  /  Cellular
