### ISSUE TITLE
How to recreate all indirect links as fail-safe?

### ISSUE THREAD

**Issue by fiedl** [resgraph/acts-as-dag#7]
Hello,

I was wondering if there is a kind of fail-safe method already to recreate all indirect links on the basis of the direct edges.

That is: If all indirect links in the dag link table were deleted and only the direct edges were left, how would I reconsruct all the indirect links?

Many thanks!
fiedl

**Comment by resgraph** [comment]
I'm thinking about this, let me get back to you.

**Comment by fiedl** [comment]
I've written a small rake task to reconstruct the indirect links by storing the direct links in an array, wiping the table and using the models own mechanisms to reconstruct the table.

``` ruby
# lib/tasks/reconstruct_indirect_dag_links.rake
namespace :reconstruct_indirect_dag_links do

  desc "Reconstruct Indirect DagLinks"
  task reconstruct_indirect_dag_links: :environment do
    STDOUT.sync = true
    p "Task: Reconstruct Indirect DagLinks"

    all_links_before_wipe = DagLink.with_deleted.where( :direct => true ).all
    num_of_dag_links_before_deletion = DagLink.with_deleted.all.count

    DagLink.transaction do

      DagLink.delete_all!

      for template_link in all_links_before_wipe

        new_link = DagLink.create( ancestor_id: template_link.ancestor_id,
                                   ancestor_type: template_link.ancestor_type,
                                   descendant_id: template_link.descendant_id,
                                   descendant_type: template_link.descendant_type,
                                   direct: true )
        new_link.created_at = template_link.created_at
        new_link.deleted_at = template_link.deleted_at if template_link.deleted_at
        new_link.save

        print ".".green

      end

    end

    print "\n"
    p "#{all_links_before_wipe.count} direct links reconstructed."
    p "There are #{DagLink.with_deleted.all.count} links in total now, including deleted."
    p "Before reconstruction, there have been #{num_of_dag_links_before_deletion}."

  end

  desc "Run all tasks"
  task :all => [
                :reconstruct_indirect_dag_links,
               ]

end
```

Please note, I'm using [rails3_acts_as_paranoid](https://github.com/goncalossilva/rails3_acts_as_paranoid) on this table, using this gem: [acts_as_paranoid_dag](https://github.com/fiedl/acts_as_paranoid_dag). 

Without this paranoid behaviour, one has to modify the above script slightly: Use `delete_all` instead of `delete_all!` and don't set the `deleted_at` attribute.

**Comment by resgraph** [comment]
Nice.
